name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.3=hab8b942_3
  - aws-c-cal=0.6.2=hb406d48_0
  - aws-c-common=0.9.0=hb547adb_0
  - aws-c-compression=0.2.17=he70778a_2
  - aws-c-event-stream=0.3.2=hcf14f3f_0
  - aws-c-http=0.7.12=he297698_1
  - aws-c-io=0.13.32=h3c776e5_2
  - aws-c-mqtt=0.9.5=h83b98fe_1
  - aws-c-s3=0.3.14=h24e141d_3
  - aws-c-sdkutils=0.1.12=he70778a_1
  - aws-checksums=0.1.17=he70778a_1
  - aws-crt-cpp=0.23.0=h04fc39a_5
  - aws-sdk-cpp=1.10.57=h0092a47_21
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blosc=1.21.4=hc338f07_0
  - boost-cpp=1.78.0=h9ed8d21_3
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotli-python=1.0.9=py311ha397e9f_9
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.19.1=hb547adb_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cairo=1.16.0=h1e71087_1016
  - cartopy=0.22.0=py311h9e438b8_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cfitsio=4.3.0=hca87796_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.0=py311he4fd1f5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.8=py311ha891d26_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - fiona=1.9.4=py311h0e2296b_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py311heffc1b2_0
  - freetype=2.12.1=hd633e50_1
  - freexl=1.0.6=h1a8c8d9_1
  - gdal=3.7.1=py311h354944d_7
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geos=3.12.0=h13dd4ca_0
  - geotiff=1.7.1=h00e2a8a_11
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - hdf4=4.2.15=h8111dcc_6
  - hdf5=1.14.2=nompi_h3aba7b3_100
  - icu=72.1=he12128b_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.25.1=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h40ed0f5_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h267d04e_0
  - kealib=1.5.1=h47b5e36_5
  - kiwisolver=1.4.5=py311he4fd1f5_0
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.15=hd835a16_1
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.0.6=hb7217d7_1
  - libarchive=3.6.2=h82b9b87_1
  - libblas=3.9.0=17_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libcblas=3.9.0=17_osxarm64_openblas
  - libcurl=8.2.1=hc52a3a8_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.18=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.7.1=hdf35568_7
  - libgfortran=5.0.0=12_3_0_hd922786_1
  - libgfortran5=12.3.0=ha3a6a3e_1
  - libglib=2.76.4=h24e9cb9_0
  - libiconv=1.17=he4db4b2_0
  - libjpeg-turbo=2.1.5.1=h1a8c8d9_0
  - libkml=1.3.0=h41464e4_1015
  - liblapack=3.9.0=17_osxarm64_openblas
  - libnetcdf=4.9.2=nompi_h8b962ec_110
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.23=openmp_hc731615_0
  - libpng=1.6.39=h76d750c_0
  - libpq=15.4=hcea71ed_0
  - librttopo=1.1.0=h667cd51_14
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.0.1=h6193c13_28
  - libsqlite=3.43.0=hb31c410_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.5.1=h23a1a89_1
  - libwebp-base=1.3.1=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.11.5=he3bdae6_0
  - libzip=1.10.1=ha0bc3c6_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=16.0.6=h1c12783_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h642e427_1000
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.3=py311heffc1b2_0
  - matplotlib-base=3.7.2=py311h3bc9839_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h7ea286d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.92=hc6b9969_0
  - numpy=1.25.2=py311hb8f3215_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.2=h53f4e23_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311h9e438b8_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.0=py311h095fde6_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.08.0=h16d8c84_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.4=h00cd704_0
  - proj=9.2.1=h8fdea58_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311he2be06e_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.6.0=py311h280d66e_1
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.5=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyzmq=25.1.1=py311hb1af645_0
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rtree=1.0.1=py311hd698ff7_2
  - scikit-learn=1.3.0=py311hf0b18b8_0
  - scipy=1.11.2=py311h93d07a4_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - shapely=2.0.1=py311h7089352_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h17c5cce_0
  - sqlite=3.43.0=h203b68d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.16.3=hc77a09f_1
  - tk=8.6.12=he1e0b03_0
  - tornado=6.3.3=py311heffc1b2_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzcode=2023c=h1a8c8d9_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xerces-c=3.2.4=h68f8447_2
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
prefix: /Users/c.sandovalolascoaga/anaconda3/envs/geo_env
